apps/config/routes.rb
Rails.application.routes.draw do
  devise_for :admins # 追加
  devise_for :users # 追加
  resources :prefectures
  resources :calenders
  resources :rooms

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "rooms#index"
end

apps/app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :rooms, dependent: :destroy       
end

apps/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

apps/app/models/calender.rb
class Calender < ApplicationRecord
end

apps/app/models/prefecture.rb
class Prefecture < ApplicationRecord
end

apps/app/models/room.rb
class Room < ApplicationRecord
end

apps/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

apps/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    protect_from_forgery with: :exception
    
    before_action :permit_params, if: :devise_controller?

    def permit_params
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
        devise_parameter_sanitizer.permit(:sign_in, keys: [:remember_created_at])
    end
end

apps/app/controllers/calenders_controller.rb
class CalendersController < ApplicationController
  before_action :set_calender, only: %i[ show edit update destroy ]

  # GET /calenders or /calenders.json
  def index
    @calenders = Calender.all
  end

  # GET /calenders/1 or /calenders/1.json
  def show
  end

  # GET /calenders/new
  def new
    @calender = Calender.new
  end

  # GET /calenders/1/edit
  def edit
  end

  # POST /calenders or /calenders.json
  def create
    @calender = Calender.new(calender_params)

    respond_to do |format|
      if @calender.save
        format.html { redirect_to @calender, notice: "Calender was successfully created." }
        format.json { render :show, status: :created, location: @calender }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @calender.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /calenders/1 or /calenders/1.json
  def update
    respond_to do |format|
      if @calender.update(calender_params)
        format.html { redirect_to @calender, notice: "Calender was successfully updated." }
        format.json { render :show, status: :ok, location: @calender }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @calender.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /calenders/1 or /calenders/1.json
  def destroy
    @calender.destroy

    respond_to do |format|
      format.html { redirect_to calenders_path, status: :see_other, notice: "Calender was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_calender
      @calender = Calender.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def calender_params
      params.require(:calender).permit(:day, :begin_time, :close_time, :interval_s, :interval_e, :unit_minute, :no_use)
    end
end

apps/app/controllers/prefectures_controller.rb
class PrefecturesController < ApplicationController
  before_action :set_prefecture, only: %i[ show edit update destroy ]

  # GET /prefectures or /prefectures.json
  def index
    @prefectures = Prefecture.all
  end

  # GET /prefectures/1 or /prefectures/1.json
  def show
  end

  # GET /prefectures/new
  def new
    @prefecture = Prefecture.new
  end

  # GET /prefectures/1/edit
  def edit
  end

  # POST /prefectures or /prefectures.json
  def create
    @prefecture = Prefecture.new(prefecture_params)

    respond_to do |format|
      if @prefecture.save
        format.html { redirect_to @prefecture, notice: "Prefecture was successfully created." }
        format.json { render :show, status: :created, location: @prefecture }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @prefecture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prefectures/1 or /prefectures/1.json
  def update
    respond_to do |format|
      if @prefecture.update(prefecture_params)
        format.html { redirect_to @prefecture, notice: "Prefecture was successfully updated." }
        format.json { render :show, status: :ok, location: @prefecture }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @prefecture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prefectures/1 or /prefectures/1.json
  def destroy
    @prefecture.destroy

    respond_to do |format|
      format.html { redirect_to prefectures_path, status: :see_other, notice: "Prefecture was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prefecture
      @prefecture = Prefecture.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def prefecture_params
      params.require(:prefecture).permit(:name, :key)
    end
end

apps/app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[ show edit update destroy ]

  # GET /rooms or /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1 or /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms or /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: "Room was successfully created." }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1 or /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: "Room was successfully updated." }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1 or /rooms/1.json
  def destroy
    @room.destroy

    respond_to do |format|
      format.html { redirect_to rooms_path, status: :see_other, notice: "Room was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.require(:room).permit(:name, :profile)
    end
end

apps/app/helpers/application_helper.rb
module ApplicationHelper
end

apps/app/helpers/calenders_helper.rb
module CalendersHelper
end

apps/app/helpers/prefectures_helper.rb
module PrefecturesHelper
end

apps/app/helpers/rooms_helper.rb
module RoomsHelper
end

apps/app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

apps/app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "ログイン", new_session_path(resource_name), class: "ml-2 lnk_btn" %>
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "登録", new_registration_path(resource_name), class: "ml-2 lnk_btn" %>
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "パスワード忘れ?", new_password_path(resource_name), class: "ml-2 lnk_btn" %>
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name), class: "ml-2 lnk_btn" %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name), class: "ml-2 lnk_btn" %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

apps/app/views/calenders/_calender.html.erb
<div id="<%= dom_id calender %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Day:</strong>
    <%= calender.day %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Begin time:</strong>
    <%= calender.begin_time %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Close time:</strong>
    <%= calender.close_time %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Interval s:</strong>
    <%= calender.interval_s %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Interval e:</strong>
    <%= calender.interval_e %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Unit minute:</strong>
    <%= calender.unit_minute %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">No use:</strong>
    <%= calender.no_use %>
  </p>

</div>

apps/app/views/calenders/_form.html.erb
<%= form_with(model: calender, class: "contents") do |form| %>
  <% if calender.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(calender.errors.count, "error") %> prohibited this calender from being saved:</h2>

      <ul>
        <% calender.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :day %>
    <%= form.date_field :day, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :begin_time %>
    <%= form.datetime_field :begin_time, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :close_time %>
    <%= form.datetime_field :close_time, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :interval_s %>
    <%= form.datetime_field :interval_s, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :interval_e %>
    <%= form.datetime_field :interval_e, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :unit_minute %>
    <%= form.number_field :unit_minute, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :no_use %>
    <%= form.check_box :no_use, class: "block mt-2 h-5 w-5" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

apps/app/views/calenders/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing calender</h1>

  <%= render "form", calender: @calender %>

  <%= link_to "Show this calender", @calender, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to calenders", calenders_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

apps/app/views/calenders/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Calenders" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Calenders</h1>
    <%= link_to "New calender", new_calender_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="calenders" class="min-w-full">
    <% @calenders.each do |calender| %>
      <%= render calender %>
      <p>
        <%= link_to "Show this calender", calender, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      </p>
    <% end %>
  </div>
</div>

apps/app/views/calenders/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New calender</h1>

  <%= render "form", calender: @calender %>

  <%= link_to "Back to calenders", calenders_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

apps/app/views/calenders/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @calender %>

    <%= link_to "Edit this calender", edit_calender_path(@calender), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to calenders", calenders_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this calender", @calender, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>

apps/app/views/layouts/_navi.html.erb
<nav class="bg-purple-900 text-white flex justify-between">
    <ul class="px-10 py-4 flex space-x-3">
        <%= content_tag(:li, class: "cursor-pointer") do
            link_to("HOME", root_path) end if !admin_signed_in? %>
        <%= content_tag(:li, class: "cursor-pointer") do
            link_to("ルーム", rooms_path) end if admin_signed_in? %>    
        <%= content_tag(:li, class: "cursor-pointer") do
            link_to("カレンダー", calenders_path) end if admin_signed_in? %>
        <%= content_tag(:li, class: "cursor-pointer") do
            link_to("登録", new_user_registration_path) end if !user_signed_in? && !admin_signed_in? %>    
        <%= content_tag(:li, class: "cursor-pointer") do
            link_to("ログイン", new_user_session_path) end if !user_signed_in? && !admin_signed_in? %>
        <%= content_tag(:li, class: "cursor-pointer") do
            link_to("ADMINログイン", new_admin_session_path) end if !user_signed_in? && !admin_signed_in? %>
        <%= content_tag(:li, class: "cursor-pointer") do
            link_to("ログアウト", destroy_user_session_path, data: { turbo_method: :delete }) end if user_signed_in? %>
        <%= content_tag(:li, class: "cursor-pointer") do
            link_to("ADMINログアウト", destroy_user_session_path, data: { turbo_method: :delete }) end if admin_signed_in? %>    
    </ul>
</nav>

apps/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Apps</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navi' %>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

apps/app/views/prefectures/_form.html.erb
<%= form_with(model: prefecture, class: "contents") do |form| %>
  <% if prefecture.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(prefecture.errors.count, "error") %> prohibited this prefecture from being saved:</h2>

      <ul>
        <% prefecture.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :key %>
    <%= form.text_field :key, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

apps/app/views/prefectures/_prefecture.html.erb
<div id="<%= dom_id prefecture %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= prefecture.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Key:</strong>
    <%= prefecture.key %>
  </p>

</div>

apps/app/views/prefectures/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing prefecture</h1>

  <%= render "form", prefecture: @prefecture %>

  <%= link_to "Show this prefecture", @prefecture, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to prefectures", prefectures_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

apps/app/views/prefectures/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Prefectures" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Prefectures</h1>
    <%= link_to "New prefecture", new_prefecture_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="prefectures" class="min-w-full">
    <% @prefectures.each do |prefecture| %>
      <%= render prefecture %>
      <p>
        <%= link_to "Show this prefecture", prefecture, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      </p>
    <% end %>
  </div>
</div>

apps/app/views/prefectures/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New prefecture</h1>

  <%= render "form", prefecture: @prefecture %>

  <%= link_to "Back to prefectures", prefectures_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

apps/app/views/prefectures/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @prefecture %>

    <%= link_to "Edit this prefecture", edit_prefecture_path(@prefecture), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to prefectures", prefectures_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this prefecture", @prefecture, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>

apps/app/views/rooms/_form.html.erb
<%= form_with(model: room, class: "contents") do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
        <% room.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :profile %>
    <%= form.text_area :profile, rows: 4, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

apps/app/views/rooms/_room.html.erb
<div id="<%= dom_id room %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">ルーム名:</strong>
    <%= room.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">詳細案内:</strong>
    <%= room.profile %>
  </p>

</div>

apps/app/views/rooms/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">ルーム編集</h1>

  <%= render "form", room: @room %>

  <%= link_to "表示", @room, class: "lnk_btn" %>
  <%= link_to "戻る", rooms_path, class: "lnk_btn" %>
</div>

apps/app/views/rooms/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Rooms" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">ルーム一覧</h1>
    <%= link_to "新規ルーム作成", new_room_path, class: "new_btn" if admin_signed_in? %>
  </div>

  <div id="rooms" class="min-w-full">
    <% @rooms.each do |room| %>
      <%= render room %>
      <p>
        <%= link_to "詳細表示", room, class: "lnk_btn" %>
      </p>
    <% end %>
  </div>
</div>

apps/app/views/rooms/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">新規ルーム</h1>

  <%= render "form", room: @room %>

  <%= link_to "戻る", rooms_path, class: "ml-2 lnk_btn" %>
</div>

apps/app/views/rooms/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @room %>

    <%= link_to "編集", edit_room_path(@room), class: "mt-2 lnk_btn" if admin_signed_in? %>
    <%= link_to "戻る", rooms_path, class: "mt-2 lnk_btn" %>
    <div class="inline-block ml-2">
      <%= button_to "削除", @room, method: :delete, class: "mt-2 lnk_btn" if admin_signed_in? %>
    </div>
  </div>
</div>

apps/app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

apps/app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "ログイン", new_session_path(resource_name), class: "ml-2 lnk_btn" %>
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "登録", new_registration_path(resource_name), class: "ml-2 lnk_btn" %>
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "パスワード忘れ?", new_password_path(resource_name), class: "ml-2 lnk_btn" %>
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name), class: "ml-2 lnk_btn" %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name), class: "ml-2 lnk_btn" %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>